import { BlockId } from "../types";
import type { BlockDefinition } from "./types";

export const decorativeBlockDefinitions: BlockDefinition[] = [
  { id: BlockId.Cobblestone, name: "Cobblestone", frenchName: "pierres", color: [0.45, 0.45, 0.45, 1.0], solid: true, transparentForMeshing: false },
  { id: BlockId.MossyCobblestone, name: "Mossy Cobblestone", frenchName: "pierres moussues", color: [0.45, 0.45, 0.45, 1.0], solid: true, transparentForMeshing: false },
  { id: BlockId.StoneBricks, name: "Stone Bricks", frenchName: "briques de pierre", color: [0.45, 0.45, 0.45, 1.0], solid: true, transparentForMeshing: false },
  { id: BlockId.MossyStoneBricks, name: "Mossy Stone Bricks", frenchName: "briques de pierre moussues", color: [0.45, 0.45, 0.45, 1.0], solid: true, transparentForMeshing: false },
  { id: BlockId.CrackedStoneBricks, name: "Cracked Stone Bricks", frenchName: "briques de pierre craquelées", color: [0.45, 0.45, 0.45, 1.0], solid: true, transparentForMeshing: false },
  { id: BlockId.ChiseledStoneBricks, name: "Chiseled Stone Bricks", frenchName: "briques de pierre sculptées", color: [0.45, 0.45, 0.45, 1.0], solid: true, transparentForMeshing: false },
  { id: BlockId.Bricks, name: "Bricks", frenchName: "briques", color: [0.55, 0.2, 0.12, 1.0], solid: true, transparentForMeshing: false },
  { id: BlockId.Sandstone, name: "Sandstone", frenchName: "grès", color: [0.82, 0.72, 0.42, 1.0], solid: true, transparentForMeshing: false },
  { id: BlockId.RedSandstone, name: "Red Sandstone", frenchName: "grès rouge", color: [0.75, 0.33, 0.16, 1.0], solid: true, transparentForMeshing: false },
  { id: BlockId.SmoothStone, name: "Smooth Stone", frenchName: "pierre lisse", color: [0.45, 0.45, 0.45, 1.0], solid: true, transparentForMeshing: false },
  { id: BlockId.SmoothSandstone, name: "Smooth Sandstone", frenchName: "grès lisse", color: [0.82, 0.72, 0.42, 1.0], solid: true, transparentForMeshing: false },
  { id: BlockId.Netherrack, name: "Netherrack", frenchName: "netherrack", color: [0.45, 0.08, 0.08, 1.0], solid: true, transparentForMeshing: false },
  { id: BlockId.SoulSand, name: "Soul Sand", frenchName: "sable des âmes", color: [0.23, 0.16, 0.12, 1.0], solid: true, transparentForMeshing: false },
  { id: BlockId.SoulSoil, name: "Soul Soil", frenchName: "terre des âmes", color: [0.23, 0.16, 0.12, 1.0], solid: true, transparentForMeshing: false },
  { id: BlockId.Basalt, name: "Basalt", frenchName: "basalte", color: [0.08, 0.08, 0.1, 1.0], solid: true, transparentForMeshing: false },
  { id: BlockId.Blackstone, name: "Blackstone", frenchName: "pierre noire", color: [0.08, 0.08, 0.1, 1.0], solid: true, transparentForMeshing: false },
  { id: BlockId.MagmaBlock, name: "Magma Block", frenchName: "bloc de magma", color: [0.95, 0.25, 0.05, 1.0], solid: true, transparentForMeshing: false },
  { id: BlockId.Glowstone, name: "Glowstone", frenchName: "pierre lumineuse", color: [1.0, 0.82, 0.35, 1.0], solid: true, transparentForMeshing: false },
  { id: BlockId.EndStone, name: "End Stone", frenchName: "pierre de l'End", color: [0.86, 0.84, 0.55, 1.0], solid: true, transparentForMeshing: false },
  { id: BlockId.EndStoneBricks, name: "End Stone Bricks", frenchName: "briques de pierre de l'End", color: [0.86, 0.84, 0.55, 1.0], solid: true, transparentForMeshing: false },
  { id: BlockId.PurpurBlock, name: "Purpur Block", frenchName: "bloc de purpur", color: [0.55, 0.32, 0.62, 1.0], solid: true, transparentForMeshing: false },
  { id: BlockId.CraftingTable, name: "Crafting Table", frenchName: "table de craft", color: [0.5, 0.32, 0.16, 1.0], solid: true, transparentForMeshing: false },
  { id: BlockId.Furnace, name: "Furnace", frenchName: "four", color: [0.25, 0.25, 0.25, 1.0], solid: true, transparentForMeshing: false },
  { id: BlockId.Chest, name: "Chest", frenchName: "coffre", color: [0.72, 0.42, 0.12, 1.0], solid: true, transparentForMeshing: false },
  { id: BlockId.Torch, name: "Torch", frenchName: "torche", color: [1.0, 0.75, 0.18, 1.0], solid: false, transparentForMeshing: true },
  { id: BlockId.Glass, name: "Glass", frenchName: "verre", color: [0.8, 0.95, 1.0, 0.35], solid: true, transparentForMeshing: true },
  { id: BlockId.Bookshelf, name: "Bookshelf", frenchName: "bibliothèque", color: [0.45, 0.25, 0.12, 1.0], solid: true, transparentForMeshing: false },
];
