import { BlockId } from "../types";
import type { BlockDefinition, BlockTextureDefinition } from "./types";

const allFaces = (texture: BlockTextureDefinition) => ({
  top: texture,
  bottom: texture,
  front: texture,
  back: texture,
  right: texture,
  left: texture,
});

const dirtTexture: BlockTextureDefinition = {
  palette: {
    A: [0.42, 0.27, 0.16, 1],
    B: [0.50, 0.34, 0.20, 1],
    C: [0.35, 0.22, 0.13, 1],
    D: [0.60, 0.43, 0.27, 1],
    E: [0.28, 0.18, 0.11, 1],
    F: [0.68, 0.52, 0.34, 1],
    G: [0.56, 0.56, 0.50, 1],
  },
  matrix: [
    "BCDBBFACBBDCABGB",
    "DDBBBBAFBCBAABCD",
    "DDFBCFBAABDDCBAA",
    "FFBBAAABBBFDDAEE",
    "ABFDDAECBFDAABFD",
    "DGFFAEFDABFDBDCA",
    "BFFFEADBBFADBAAA",
    "DDBBBDDBCABBAAAB",
    "ABFFFBDBABADFFBB",
    "FFGDBFDBBAFFFDDB",
    "DADBBDFFFFBCDBBF",
    "FAAABABCDDDGABFD",
    "FFDABAEFDBFDCBBD",
    "DGEABDDBAFFBABFD",
    "ABBFDDBFBAAADDBF",
    "FBFDDABBFDDBDDBF",
  ],
};

const grassTopTexture: BlockTextureDefinition = {
  palette: {
    A: [0.16, 0.43, 0.10, 1],
    B: [0.20, 0.56, 0.13, 1],
    C: [0.28, 0.68, 0.18, 1],
    D: [0.35, 0.76, 0.23, 1],
  },
  matrix: [
    "ABBCDCCBABBCDCCB",
    "BCCBDDBCBCCBDDBC",
    "CDBBCCADCDBBCCAD",
    "BBACDBBCBBACDBBC",
    "DCCBABBCDCCBABBC",
    "ADDBCCBDADDBCCBD",
    "BCCADCDBBCCADCDB",
    "CDBBCBACDDBBCBAC",
    "ABBCDCCBABBCDCCB",
    "BCCBDDBCBCCBDDBC",
    "CDBBCCADCDBBCCAD",
    "BBACDBBCBBACDBBC",
    "DCCBABBCDCCBABBC",
    "ADDBCCBDADDBCCBD",
    "BCCADCDBBCCADCDB",
    "CDBBCBACDDBBCBAC",
  ],
};

const grassSideTexture: BlockTextureDefinition = {
  palette: {
    A: [0.16, 0.42, 0.11, 1],
    B: [0.22, 0.58, 0.14, 1],
    C: [0.32, 0.70, 0.22, 1],
    D: [0.42, 0.26, 0.15, 1],
    E: [0.52, 0.34, 0.20, 1],
    F: [0.34, 0.22, 0.13, 1],
    G: [0.62, 0.45, 0.28, 1],
    H: [0.55, 0.55, 0.49, 1],
  },
  matrix: [
    "ABCCBCBACCCBBCAA",
    "BCCCBCCACCCBBCAB",
    "BCACDBCACCEBCFAB",
    "DDCFBBCAGDDCFFDE",
    "FEGDEHCBFGFDEGDF",
    "DGFEFDEGDFEHGDEE",
    "GDFEDGFEGDFEDGFE",
    "DEGFDEHFGDEGFDDE",
    "FDDEGFEDEGFDHGFE",
    "EGFDEGDFEDDEGFDE",
    "DDEHGFEGFDDEGFDE",
    "FDEGDFEHFDEGDFED",
    "GDFEDDEGFDEGFDHG",
    "DEGFDEGDFEDDEGFE",
    "FDEHGFEDGDFEGDFE",
    "GDFEDGFEHDFEDGFE",
  ],
};

const stoneTexture: BlockTextureDefinition = {
  palette: {
    A: [0.56, 0.56, 0.56, 1],
    B: [0.50, 0.50, 0.50, 1],
    C: [0.45, 0.45, 0.45, 1],
    D: [0.41, 0.41, 0.41, 1],
  },
  matrix: [
    "AAAABCCBCDCCBBBB",
    "BBCBCBBBBBBDDCBC",
    "BCDDCCCDCCCBBBBB",
    "BBAABABBAABBBCCC",
    "CBBCCCBCBAAAACBB",
    "BABBBBBBBCCDCDCA",
    "CBBAAACAACCCBBBB",
    "CCDDCDCCBBCCCBBB",
    "AAABABBAAABBBBBC",
    "BBABBBAAABBAAAAB",
    "DBCBCCDDCBCBBCCC",
    "BBBBBAABBBBBAABA",
    "BCCCBABCCBBDDCDC",
    "AABCCBBCCCBBCCCA",
    "BCCBBBBBBBBBAAAA",
    "BBBBBBCCBAABBCBB",
  ],
};

const sandTexture: BlockTextureDefinition = {
  palette: {
    A: [0.98, 0.96, 0.80, 1],
    B: [0.90, 0.87, 0.68, 1],
    C: [0.86, 0.83, 0.63, 1],
    D: [0.83, 0.80, 0.59, 1],
    E: [0.76, 0.73, 0.52, 1],
  },
  matrix: [
    "ECCCBCDCBCCCCADC",
    "CCBBEDDDBBACCCCB",
    "BBADDDCCCBBBCDDA",
    "DDCCDCDCEDCBBBCE",
    "BDBDBBBBDDDBDEBE",
    "DCDADBCCDBCEDDCE",
    "ECDCECCDDCBACBCD",
    "CCBCCDBACDCDCBAB",
    "CCBBCDBCDAECDCCC",
    "ECBCCCDDCCCBCBCB",
    "CCEBEBCCBBBDCADC",
    "DBBECDCDCCCADDDE",
    "BCDBCDCEECCDCBDD",
    "CBDEDDDBCABCBDBD",
    "BCDDCDCCECEDBDDC",
    "DBCEACEBCBDCCCDE",
  ],
};

const coarseDirtTexture: BlockTextureDefinition = {
  palette: {
    A: [0.32, 0.20, 0.12, 1],
    B: [0.42, 0.27, 0.16, 1],
    C: [0.52, 0.36, 0.22, 1],
    D: [0.61, 0.47, 0.31, 1],
    E: [0.25, 0.16, 0.10, 1],
    F: [0.66, 0.62, 0.52, 1],
  },
  matrix: [
    "BBCACDBBFCBADABC",
    "CDBBBAACBBDCFBBA",
    "BAFDCBBACCBBAEBC",
    "DCCBBEABFBCDBBBA",
    "ABBCCDBBAAFBCBCD",
    "BCDBBBAECCDBBAFB",
    "CBBFDCBBCDABBCBA",
    "BBACCBDEBBCFADBB",
    "DCBBBAABCCDBBFAC",
    "BBEACDBBBAFCCBBD",
    "CFBBACBCDBBBAEAB",
    "BBADBFCBBCDABBCE",
    "ACBBBDDBAECBBBCF",
    "BBDCFBBACCBDBBAA",
    "EBBCABBDCFBBCDAB",
    "CDBBAABCBBEADBCF",
  ],
};

const podzolTopTexture: BlockTextureDefinition = {
  palette: {
    A: [0.28, 0.17, 0.08, 1],
    B: [0.36, 0.23, 0.11, 1],
    C: [0.48, 0.32, 0.16, 1],
    D: [0.16, 0.11, 0.06, 1],
    E: [0.58, 0.44, 0.22, 1],
    F: [0.20, 0.28, 0.12, 1],
  },
  matrix: [
    "BBACCBDBEFBCBABB",
    "ACDBBBCCBABDBECA",
    "CBBEADBBCFBBACBD",
    "BDBBACCBBAEDBBAC",
    "EACBBDBFCBBACDBB",
    "BBCDBBAABCEDBCBA",
    "CBBAFBBDEABCBBAC",
    "DBBCCBAABBCFDBBE",
    "BBAECDBBCBBAACBD",
    "ACBBCFDBBEACBBBA",
    "CDBBBAACBDBBFECB",
    "BBACCBEDBBAABCDB",
    "FDBBACBBCCBDEABB",
    "BCBBAEDBBCACBBDF",
    "ABBCDBBAFCBBEACB",
    "CBBACBDBBAEBCDBB",
  ],
};

const podzolSideTexture: BlockTextureDefinition = {
  palette: {
    A: [0.33, 0.22, 0.11, 1],
    B: [0.42, 0.27, 0.15, 1],
    C: [0.52, 0.35, 0.20, 1],
    D: [0.27, 0.17, 0.09, 1],
    E: [0.60, 0.45, 0.26, 1],
  },
  matrix: [
    "ABCBCCBABCCBACBA",
    "BCDBCBACBBCACBCB",
    "CBACCEBCBDBCBACB",
    "DDBBCCBAEDDBCBBD",
    "BCDBEADBBCDBBCBA",
    "CBBADBCDBEABCDBB",
    "DBCBBCBACDBBCBBA",
    "BBCDBEABBCCBDBCB",
    "CBACBBDCBBAECDBB",
    "DBBCBABCDBBCBABC",
    "BBAECDBBCBBAEDCB",
    "CDBBABCDBBACBBCD",
    "BBCDBBAECDBBCBBA",
    "CBBAEDBBCABCDDBB",
    "DBBCBAECBBDCBCBA",
    "BBCDBBACDBBABCBE",
  ],
};

const rootedDirtTexture: BlockTextureDefinition = {
  palette: {
    A: [0.36, 0.23, 0.13, 1],
    B: [0.45, 0.29, 0.17, 1],
    C: [0.55, 0.38, 0.23, 1],
    D: [0.27, 0.17, 0.10, 1],
    E: [0.70, 0.54, 0.34, 1],
    F: [0.78, 0.66, 0.45, 1],
  },
  matrix: [
    "BBCACDBBFCBADABC",
    "CDBBBAACBBCDFBBA",
    "BAFDCBBACCBBAEBC",
    "DCCBBEABFBCDBBBA",
    "ABBFCCBBAAFBCBCD",
    "BFCBBBAECCDBBAFB",
    "CBBFDCBBCDABBCBA",
    "BBACCBDEBBCFADBB",
    "DCBBBAABCCDBBFAC",
    "BBEACDBBBAFCCBBD",
    "CFBBACBCDBBBAEAB",
    "BBADBFCBBCDABBCE",
    "ACBBBDDBAECBBBCF",
    "BBDCFBBACCBDBBAA",
    "EBBCABBDCFBBCDAB",
    "CDBBAABCBBEADBCF",
  ],
};

const deepslateTexture: BlockTextureDefinition = {
  palette: {
    A: [0.14, 0.14, 0.16, 1],
    B: [0.18, 0.18, 0.20, 1],
    C: [0.22, 0.22, 0.24, 1],
    D: [0.10, 0.10, 0.12, 1],
    E: [0.29, 0.29, 0.31, 1],
  },
  matrix: [
    "ABBCCBBAABBDCCBA",
    "BBCBBDCCBBAABBCD",
    "CBBDDBAABBCCBBAA",
    "DCCBBAAEBBCDDBBA",
    "BBACECCBBAABBDCC",
    "CDBBAABBCDCCBBAA",
    "BBCCDDBBAACCBBCD",
    "AABBDCCBBAABBCCD",
    "CCBBAABBDCCBBAAE",
    "BBDCCBBAABBCDDBA",
    "DDBBAACCBBCDCCBB",
    "BBCCBBAAECCBBAAB",
    "AABBCDDBBAACCBBC",
    "CCBBAABBDCCBBAAD",
    "BBAECCBBDDBBAACC",
    "DCCBBAABBCDDBBAA",
  ],
};

const graniteTexture: BlockTextureDefinition = {
  palette: {
    A: [0.45, 0.27, 0.23, 1],
    B: [0.56, 0.35, 0.28, 1],
    C: [0.66, 0.43, 0.34, 1],
    D: [0.36, 0.22, 0.18, 1],
    E: [0.75, 0.55, 0.46, 1],
    F: [0.52, 0.48, 0.43, 1],
  },
  matrix: [
    "BBCACDBBECBADABC",
    "CDBBBAACBBECFBBA",
    "BAFDCBBACCBBAEBC",
    "DCCBBEABFBCDBBBA",
    "ABBCCDBBAAFBCBCE",
    "BCDBBBAECCDBBAFB",
    "CBBFDCBBCDABBCBA",
    "BBACCBDEBBCFADBB",
    "DCBBBAABCCDBBFAC",
    "BBEACDBBBAFCCBBD",
    "CFBBACBCDBBBAEAB",
    "BBADBFCBBCDABBCE",
    "ACBBBDDBAECBBBCF",
    "BBDCFBBACCBDBBAA",
    "EBBCABBDCFBBCDAB",
    "CDBBAABCBBEADBCF",
  ],
};

const dioriteTexture: BlockTextureDefinition = {
  palette: {
    A: [0.62, 0.62, 0.60, 1],
    B: [0.74, 0.74, 0.72, 1],
    C: [0.86, 0.86, 0.84, 1],
    D: [0.45, 0.45, 0.43, 1],
    E: [0.94, 0.93, 0.88, 1],
    F: [0.30, 0.30, 0.30, 1],
  },
  matrix: [
    "BCCBBDCACCEBDBBC",
    "CBBAACBCDBBCEBBA",
    "ACCEBDBBCBAADBBC",
    "DDBBCBACECCBBAFB",
    "BBCEACBBDDBBACCE",
    "CEBBCADBBCBBAACB",
    "BBAACCEBDBBCDBBA",
    "DBBCCBAACEBBACCD",
    "ACCEBBAADBBCBECB",
    "CBBACCEBBDDBBAAC",
    "EADBBCBBAACCEBBD",
    "BBCEBBDDBAACCBBA",
    "CCBBAACEDBBCBBAA",
    "BBDDBBACCEBBAACB",
    "EBCBAADBBCBACEBB",
    "CBBAACCEBBDDBBAC",
  ],
};

const andesiteTexture: BlockTextureDefinition = {
  palette: {
    A: [0.34, 0.34, 0.34, 1],
    B: [0.42, 0.42, 0.42, 1],
    C: [0.50, 0.50, 0.49, 1],
    D: [0.27, 0.27, 0.27, 1],
    E: [0.58, 0.58, 0.56, 1],
  },
  matrix: [
    "BBCACDBBCCBADABC",
    "CDBBBAACBBCDBBBA",
    "BAEDCBBACCBBAEBC",
    "DCCBBEABBBCDBBBA",
    "ABBCCDBBAAEBBBCD",
    "BCDBBBAECCDBBAEB",
    "CBBEDCBBCDABBCBA",
    "BBACCBDEBBCDADBB",
    "DCBBBAABCCDBBEAC",
    "BBEACDBBBACCCBBD",
    "CDBBACBCDBBBAEAB",
    "BBADBCCBBCDABBCE",
    "ACBBBDDBAECBBBCD",
    "BBDCCBBACCBDBBAA",
    "EBBCABBDCCBBCDAB",
    "CDBBAABCBBEADBCD",
  ],
};

const tuffTexture: BlockTextureDefinition = {
  palette: {
    A: [0.25, 0.27, 0.25, 1],
    B: [0.32, 0.34, 0.32, 1],
    C: [0.40, 0.42, 0.39, 1],
    D: [0.20, 0.21, 0.20, 1],
    E: [0.48, 0.50, 0.46, 1],
  },
  matrix: [
    "ABBCCBBAABDCCBBA",
    "BBCBBDCCBBAABBCD",
    "CBBDDCAABBCCBBAA",
    "DCCBBAAEBBCDDBBA",
    "BBACECCBBAABBDCC",
    "CDBBAABBCDCCBBAA",
    "BBCCDDBBAACCBBCD",
    "AABBDCCBBAABBCCD",
    "CCBBAABBDCCBBAAE",
    "BBDCCBBAABBCDDBA",
    "DDBBAACCBBCDCCBB",
    "BBCCBBAAECCBBAAB",
    "AABBCDDBBAACCBBC",
    "CCBBAABBDCCBBAAD",
    "BBAECCBBDDBBAACC",
    "DCCBBAABBCDDBBAA",
  ],
};

const calciteTexture: BlockTextureDefinition = {
  palette: {
    A: [0.72, 0.70, 0.64, 1],
    B: [0.82, 0.80, 0.74, 1],
    C: [0.91, 0.89, 0.82, 1],
    D: [0.62, 0.60, 0.55, 1],
    E: [0.98, 0.96, 0.88, 1],
  },
  matrix: [
    "BCCBBDCACCEBDBBC",
    "CBBAACBCDBBCEBBA",
    "ACCEBDBBCBAADBBC",
    "DDBBCBACECCBBAAB",
    "BBCEACBBDDBBACCE",
    "CEBBCADBBCBBAACB",
    "BBAACCEBDBBCDBBA",
    "DBBCCBAACEBBACCD",
    "ACCEBBAADBBCBECB",
    "CBBACCEBBDDBBAAC",
    "EADBBCBBAACCEBBD",
    "BBCEBBDDBAACCBBA",
    "CCBBAACEDBBCBBAA",
    "BBDDBBACCEBBAACB",
    "EBCBAADBBCBACEBB",
    "CBBAACCEBBDDBBAC",
  ],
};

const gravelTexture: BlockTextureDefinition = {
  palette: {
    A: [0.29, 0.28, 0.27, 1],
    B: [0.39, 0.38, 0.36, 1],
    C: [0.48, 0.47, 0.44, 1],
    D: [0.22, 0.21, 0.20, 1],
    E: [0.58, 0.57, 0.53, 1],
    F: [0.68, 0.66, 0.60, 1],
  },
  matrix: [
    "BBCACDBBFCBADABC",
    "CDBBBAACBBCDFBBA",
    "BAFDCBBACCBBAEBC",
    "DCCBBEABFBCDBBBA",
    "ABBCCDBBAAFBCBCD",
    "BCDBBBAECCDBBAFB",
    "CBBFDCBBCDABBCBA",
    "BBACCBDEBBCFADBB",
    "DCBBBAABCCDBBFAC",
    "BBEACDBBBAFCCBBD",
    "CFBBACBCDBBBAEAB",
    "BBADBFCBBCDABBCE",
    "ACBBBDDBAECBBBCF",
    "BBDCFBBACCBDBBAA",
    "EBBCABBDCFBBCDAB",
    "CDBBAABCBBEADBCF",
  ],
};

const redSandTexture: BlockTextureDefinition = {
  palette: {
    A: [0.93, 0.52, 0.24, 1],
    B: [0.80, 0.39, 0.18, 1],
    C: [0.70, 0.31, 0.14, 1],
    D: [0.61, 0.25, 0.11, 1],
    E: [0.50, 0.20, 0.09, 1],
  },
  matrix: [
    "ECCCBCDCBCCCCADC",
    "CCBBEDDDBBACCCCB",
    "BBADDDCCCBBBCDDA",
    "DDCCDCDCEDCBBBCE",
    "BDBDBBBBDDDBDEBE",
    "DCDADBCCDBCEDDCE",
    "ECDCECCDDCBACBCD",
    "CCBCCDBACDCDCBAB",
    "CCBBCDBCDAECDCCC",
    "ECBCCCDDCCCBCBCB",
    "CCEBEBCCBBBDCADC",
    "DBBECDCDCCCADDDE",
    "BCDBCDCEECCDCBDD",
    "CBDEDDDBCABCBDBD",
    "BCDDCDCCECEDBDDC",
    "DBCEACEBCBDCCCDE",
  ],
};

const clayTexture: BlockTextureDefinition = {
  palette: {
    A: [0.39, 0.43, 0.48, 1],
    B: [0.48, 0.52, 0.58, 1],
    C: [0.56, 0.60, 0.66, 1],
    D: [0.33, 0.36, 0.41, 1],
    E: [0.65, 0.68, 0.72, 1],
  },
  matrix: [
    "ABBCCBBAABBDCCBA",
    "BBCBBDCCBBAABBCD",
    "CBBDDBAABBCCBBAA",
    "DCCBBAAEBBCDDBBA",
    "BBACECCBBAABBDCC",
    "CDBBAABBCDCCBBAA",
    "BBCCDDBBAACCBBCD",
    "AABBDCCBBAABBCCD",
    "CCBBAABBDCCBBAAE",
    "BBDCCBBAABBCDDBA",
    "DDBBAACCBBCDCCBB",
    "BBCCBBAAECCBBAAB",
    "AABBCDDBBAACCBBC",
    "CCBBAABBDCCBBAAD",
    "BBAECCBBDDBBAACC",
    "DCCBBAABBCDDBBAA",
  ],
};

export const terrainBlockDefinitions: BlockDefinition[] = [
  { id: BlockId.Air, name: "Air", frenchName: "air", color: [1.0, 1.0, 1.0, 0.0], solid: false, transparentForMeshing: true },
  {
    id: BlockId.GrassBlock,
    name: "Grass Block",
    frenchName: "bloc d'herbe",
    color: [0.25, 0.65, 0.2, 1.0],
    solid: true,
    transparentForMeshing: false,
    textures: {
      top: grassTopTexture,
      bottom: dirtTexture,
      front: grassSideTexture,
      back: grassSideTexture,
      right: grassSideTexture,
      left: grassSideTexture,
    },
  },
  {
    id: BlockId.Dirt,
    name: "Dirt",
    frenchName: "terre",
    color: [0.45, 0.28, 0.12, 1.0],
    solid: true,
    transparentForMeshing: false,
    textures: allFaces(dirtTexture),
  },
  { id: BlockId.CoarseDirt, name: "Coarse Dirt", frenchName: "terre stérile", color: [0.45, 0.28, 0.12, 1.0], solid: true, transparentForMeshing: false, textures: allFaces(coarseDirtTexture) },
  {
    id: BlockId.Podzol,
    name: "Podzol",
    frenchName: "podzol",
    color: [0.36, 0.23, 0.11, 1.0],
    solid: true,
    transparentForMeshing: false,
    textures: {
      top: podzolTopTexture,
      bottom: dirtTexture,
      front: podzolSideTexture,
      back: podzolSideTexture,
      right: podzolSideTexture,
      left: podzolSideTexture,
    },
  },
  { id: BlockId.RootedDirt, name: "Rooted Dirt", frenchName: "terre racineuse", color: [0.45, 0.28, 0.12, 1.0], solid: true, transparentForMeshing: false, textures: allFaces(rootedDirtTexture) },
  { id: BlockId.Stone, name: "Stone", frenchName: "pierre", color: [0.45, 0.45, 0.45, 1.0], solid: true, transparentForMeshing: false, textures: allFaces(stoneTexture) },
  { id: BlockId.Deepslate, name: "Deepslate", frenchName: "ardoise des abîmes", color: [0.18, 0.18, 0.2, 1.0], solid: true, transparentForMeshing: false, textures: allFaces(deepslateTexture) },
  { id: BlockId.Granite, name: "Granite", frenchName: "granite", color: [0.58, 0.36, 0.29, 1.0], solid: true, transparentForMeshing: false, textures: allFaces(graniteTexture) },
  { id: BlockId.Diorite, name: "Diorite", frenchName: "diorite", color: [0.78, 0.78, 0.76, 1.0], solid: true, transparentForMeshing: false, textures: allFaces(dioriteTexture) },
  { id: BlockId.Andesite, name: "Andesite", frenchName: "andésite", color: [0.42, 0.42, 0.42, 1.0], solid: true, transparentForMeshing: false, textures: allFaces(andesiteTexture) },
  { id: BlockId.Tuff, name: "Tuff", frenchName: "tuf", color: [0.32, 0.34, 0.32, 1.0], solid: true, transparentForMeshing: false, textures: allFaces(tuffTexture) },
  { id: BlockId.Calcite, name: "Calcite", frenchName: "calcite", color: [0.86, 0.84, 0.78, 1.0], solid: true, transparentForMeshing: false, textures: allFaces(calciteTexture) },
  { id: BlockId.Gravel, name: "Gravel", frenchName: "gravier", color: [0.42, 0.4, 0.38, 1.0], solid: true, transparentForMeshing: false, textures: allFaces(gravelTexture) },
  {
    id: BlockId.Sand,
    name: "Sand",
    frenchName: "sable",
    color: [0.82, 0.72, 0.42, 1.0],
    solid: true,
    transparentForMeshing: false,
    textures: allFaces(sandTexture),
  },
  { id: BlockId.RedSand, name: "Red Sand", frenchName: "sable rouge", color: [0.75, 0.33, 0.16, 1.0], solid: true, transparentForMeshing: false, textures: allFaces(redSandTexture) },
  { id: BlockId.Clay, name: "Clay", frenchName: "argile", color: [0.48, 0.52, 0.58, 1.0], solid: true, transparentForMeshing: false, textures: allFaces(clayTexture) },
];
