/**
 * Matrices de couleur pour un personnage cubique type Steve.
 *
 * Important :
 * - Ce n'est PAS un bloc 16x16.
 * - Les dimensions changent selon la face du cuboïde.
 *
 * Tête :
 * - toutes les faces : 8x8
 *
 * Torse :
 * - front/back : 8x12
 * - left/right : 4x12
 * - top/bottom : 8x4
 *
 * Bras :
 * - front/back/left/right : 4x12
 * - top/bottom : 4x4
 *
 * Jambes :
 * - front/back/left/right : 4x12
 * - top/bottom : 4x4
 */
export const stevePalette = {
  // cheveux
  A: [0.12, 0.07, 0.03, 1],
  B: [0.19, 0.10, 0.04, 1],
  C: [0.27, 0.15, 0.06, 1],
  D: [0.34, 0.20, 0.09, 1],

  // peau
  E: [0.46, 0.26, 0.16, 1],
  F: [0.60, 0.36, 0.22, 1],
  G: [0.72, 0.46, 0.30, 1],
  H: [0.82, 0.56, 0.38, 1],
  I: [0.90, 0.66, 0.46, 1],

  // visage
  J: [0.96, 0.94, 0.90, 1],
  K: [0.19, 0.12, 0.68, 1],
  L: [0.28, 0.12, 0.07, 1],
  M: [0.45, 0.20, 0.12, 1],

  // t-shirt cyan
  N: [0.00, 0.50, 0.58, 1],
  O: [0.00, 0.62, 0.68, 1],
  P: [0.05, 0.72, 0.76, 1],
  Q: [0.12, 0.78, 0.80, 1],
  R: [0.00, 0.42, 0.48, 1],

  // pantalon bleu
  S: [0.12, 0.12, 0.45, 1],
  T: [0.16, 0.16, 0.58, 1],
  U: [0.20, 0.20, 0.68, 1],
  V: [0.10, 0.10, 0.35, 1],

  // chaussures / ombres
  W: [0.18, 0.18, 0.18, 1],
  X: [0.28, 0.28, 0.28, 1],
  Y: [0.38, 0.38, 0.36, 1],
  Z: [0.08, 0.08, 0.08, 1],
} as const;

export type StevePaletteKey = keyof typeof stevePalette;

export type SteveTextureDefinition = {
  palette: { readonly [K: string]: readonly number[]};
  width: number;
  height: number;
  matrix: string[];
};

const tx = (width: number, height: number, matrix: string[]): SteveTextureDefinition => {
  if (matrix.length !== height) {
    throw new Error(`Invalid matrix height: expected ${height}, got ${matrix.length}`);
  }

  for (const row of matrix) {
    if (row.length !== width) {
      throw new Error(`Invalid matrix width: expected ${width}, got ${row.length} for row "${row}"`);
    }
  }

  return {
    palette: stevePalette,
    width,
    height,
    matrix,
  };
};

export const steveModelTextures = {
  head: {
    top: tx(8, 8, [
        "ABBCBBAA",
        "BCCDCBBA",
        "BCDDDCBA",
        "ACDCCDCA",
        "BCCDDCBA",
        "ABCDCBBA",
        "AACBCBAA",
        "AABBAAAA",
      ]),
    bottom: tx(8, 8, [
        "FGGGHGFF",
        "GGHHIHGF",
        "GHHIHHGG",
        "FHHHHHGF",
        "GGHHHGFF",
        "FGGHHGGF",
        "FFGGGFFF",
        "EFFFGFFE",
      ]),
    front: {
      width: 8,
      height: 8,
      palette: {
          A: [0.24, 0.17, 0.09, 1],
          B: [0.67, 0.51, 0.42, 1],
          C: [0.96, 0.96, 0.97, 1],
          D: [0.48, 0.33, 0.22, 1],
          E: [0.24, 0.12, 0.59, 1],
          F: [0.16, 0.11, 0.04, 1],
          G: [0.59, 0.44, 0.33, 1],
          H: [0.44, 0.28, 0.20, 1],
          I: [0.56, 0.39, 0.28, 1],
          J: [0.69, 0.55, 0.47, 1],
          K: [0.28, 0.19, 0.11, 1],
          L: [0.38, 0.24, 0.18, 1],
          M: [0.91, 0.89, 0.94, 1],
          N: [0.63, 0.47, 0.41, 1],
          O: [0.22, 0.12, 0.03, 1],
          P: [0.26, 0.15, 0.07, 1],
      },
      matrix: [
          "FFFFFFFF",
          "FAAKKKAF",
          "ABBJBBGK",
          "NBNNGBII",
          "JCENJEMJ",
          "IBNLLNGD",
          "IIPHHKDD",
          "HHOPPODD",
      ],
    } as SteveTextureDefinition,
    back: tx(8, 8, [
        "ABBCCBBA",
        "BBCDDCBA",
        "BCDCDDCA",
        "ACDDDCBA",
        "BCDCCDBA",
        "BBCDCBBA",
        "ABBCCBAA",
        "AABBBBAA",
      ]),
    left: tx(8, 8, [
        "ABBBCCBA",
        "BBCDCCBA",
        "BCDDDCBA",
        "BGGGGGGB",
        "GGGHHHGF",
        "GGHHGGGF",
        "FGGGGGFF",
        "FFGGGFFF",
      ]),
    right: tx(8, 8, [
        "ABCCBBBA",
        "ABCCDDBB",
        "ABCDDDCB",
        "BGGGGGGB",
        "FGHHHGGG",
        "FGGGHHGG",
        "FFGGGGGF",
        "FFFGGGFF",
      ])
  },
  torso: {
    front: tx(8, 12, [
        "POOQPOOP",
        "OPPPQOPO",
        "POOQPOOP",
        "OOPPRPOO",
        "OOPRRPOO",
        "PONNNNOP",
        "OPNNNNPO",
        "OONNNNOO",
        "TTTTTTTT",
        "TUTTUUTT",
        "TTUUUTTT",
        "TUTTTUTT",
      ]),
    back: tx(8, 12, [
        "OPPOQOOP",
        "POOOPQPO",
        "OPOQPOOP",
        "OPPRPOOP",
        "OOPRROPO",
        "OONNNNOO",
        "PNNNNNOP",
        "OONNNNOO",
        "TTTTTTTT",
        "TTUUTUTT",
        "TUTTTUTT",
        "TTUTTUTT",
      ]),
    left: tx(4, 12, [
        "OPOP",
        "PPQO",
        "OPPO",
        "OORO",
        "OPRO",
        "ONNO",
        "PNNO",
        "ONNO",
        "TTTT",
        "TUTT",
        "TTUT",
        "TUTT",
      ]),
    right: tx(4, 12, [
        "POPO",
        "OQPP",
        "OPPO",
        "OROO",
        "ORPO",
        "ONNO",
        "ONNP",
        "ONNO",
        "TTTT",
        "TTUT",
        "TUTT",
        "TTUT",
      ]),
    top: tx(8, 4, [
        "OPPOQOOP",
        "POOQPOOP",
        "OPPPQOPO",
        "POOPOOQP",
      ]),
    bottom: tx(8, 4, [
        "STTUTTTS",
        "TTUUUTTT",
        "TUTTTUTT",
        "STTTTUTS",
      ])
  },
  rightArm: {
    front: tx(4, 12, [
        "OQPO",
        "OPPO",
        "OPRO",
        "FHHG",
        "GGHG",
        "FGGF",
        "GGHF",
        "FGGF",
        "GGHG",
        "FHHG",
        "FGGF",
        "EFFG",
      ]),
    back: tx(4, 12, [
        "OPPO",
        "POQO",
        "OPRO",
        "GHGF",
        "GGFG",
        "GHHG",
        "FGGF",
        "GGHF",
        "FGGF",
        "GHHG",
        "FGGF",
        "FEFG",
      ]),
    left: tx(4, 12, [
        "OOPO",
        "PQOP",
        "OPRO",
        "GGHF",
        "FGGF",
        "GGHG",
        "FHHG",
        "GGFG",
        "FGGF",
        "GGHF",
        "FGGF",
        "EFFG",
      ]),
    right: tx(4, 12, [
        "POOO",
        "POQP",
        "ORPO",
        "FHHG",
        "GGFG",
        "FGGF",
        "GHHG",
        "FGGF",
        "GGHF",
        "FHHG",
        "GFGF",
        "FEFG",
      ]),
    top: tx(4, 4, [
        "OPQO",
        "POOP",
        "OPPO",
        "ROOR",
      ]),
    bottom: tx(4, 4, [
        "FGGF",
        "GHHG",
        "FGGF",
        "EFFG",
      ])
  },
  leftArm: {
    front: tx(4, 12, [
        "OPOQ",
        "OPPO",
        "ORPO",
        "GHHF",
        "GHGG",
        "FGGF",
        "FHGG",
        "FGGF",
        "GHGG",
        "GHHF",
        "FGGF",
        "GFFE",
      ]),
    back: tx(4, 12, [
        "OPPO",
        "OQOP",
        "ORPO",
        "FHGG",
        "GFGG",
        "GHHG",
        "FGGF",
        "FHGG",
        "FGGF",
        "GHHG",
        "FGGF",
        "GFEF",
      ]),
    left: tx(4, 12, [
        "OOOP",
        "PQOP",
        "ORPO",
        "GHHF",
        "GFGG",
        "FGGF",
        "GHHG",
        "FGGF",
        "FHGG",
        "GHHF",
        "FGFG",
        "GFEF",
      ]),
    right: tx(4, 12, [
        "OPOO",
        "POQP",
        "OPRO",
        "FHGG",
        "FGGF",
        "GHGG",
        "GHHF",
        "GGFG",
        "FGGF",
        "FHGG",
        "FGGF",
        "GFFE",
      ]),
    top: tx(4, 4, [
        "OQPO",
        "POOP",
        "OPPO",
        "ROOR",
      ]),
    bottom: tx(4, 4, [
        "GFGF",
        "GHHG",
        "FGGF",
        "GFFE",
      ])
  },
  rightLeg: {
    front: tx(4, 12, [
        "TUTT",
        "TTUU",
        "TUTT",
        "UTTT",
        "TTUT",
        "TUTT",
        "TTTU",
        "TUTT",
        "XXXX",
        "WXXW",
        "WWXW",
        "ZZZZ",
      ]),
    back: tx(4, 12, [
        "TTUT",
        "TUTT",
        "TTUU",
        "TUTT",
        "UTTT",
        "TTUT",
        "TUTT",
        "TTTU",
        "XXXX",
        "WXWW",
        "WXXW",
        "ZZZZ",
      ]),
    left: tx(4, 12, [
        "TTTU",
        "TUTT",
        "TTUT",
        "TUTT",
        "TTUU",
        "TUTT",
        "UTTT",
        "TTUT",
        "XXXX",
        "WWXW",
        "WXXW",
        "ZZZZ",
      ]),
    right: tx(4, 12, [
        "UTTT",
        "TTUT",
        "TUTT",
        "TTUU",
        "TUTT",
        "UTTT",
        "TTUT",
        "TUTT",
        "XXXX",
        "WXXW",
        "WXWW",
        "ZZZZ",
      ]),
    top: tx(4, 4, [
        "STTS",
        "TTUT",
        "TUTT",
        "STTS",
      ]),
    bottom: tx(4, 4, [
        "WWWW",
        "WXXW",
        "WXWW",
        "ZZZZ",
      ])
  },
  leftLeg: {
    front: tx(4, 12, [
        "TTUT",
        "UUTT",
        "TTUT",
        "TTTU",
        "TUTT",
        "TTUT",
        "UTTT",
        "TTUT",
        "XXXX",
        "WXXW",
        "WXWW",
        "ZZZZ",
      ]),
    back: tx(4, 12, [
        "TUTT",
        "TTUT",
        "UUTT",
        "TTUT",
        "TTTU",
        "TUTT",
        "TTUT",
        "UTTT",
        "XXXX",
        "WWXW",
        "WXXW",
        "ZZZZ",
      ]),
    left: tx(4, 12, [
        "TTTU",
        "TUTT",
        "TTUT",
        "UUTT",
        "TTUT",
        "TTTU",
        "TUTT",
        "TTUT",
        "XXXX",
        "WXWW",
        "WXXW",
        "ZZZZ",
      ]),
    right: tx(4, 12, [
        "UTTT",
        "TTTU",
        "TUTT",
        "TTUT",
        "UUTT",
        "TTUT",
        "TTTU",
        "TUTT",
        "XXXX",
        "WXXW",
        "WWXW",
        "ZZZZ",
      ]),
    top: tx(4, 4, [
        "STTS",
        "TUTT",
        "TTUT",
        "STTS",
      ]),
    bottom: tx(4, 4, [
        "WWWW",
        "WXWW",
        "WXXW",
        "ZZZZ",
      ])
  }
} as const;

export const steveTextures = {
  "head.top": tx(8, 8, [
    "ABBCBBAA",
    "BCCDCBBA",
    "BCDDDCBA",
    "ACDCCDCA",
    "BCCDDCBA",
    "ABCDCBBA",
    "AACBCBAA",
    "AABBAAAA",
  ]),
  "head.bottom": tx(8, 8, [
    "FGGGHGFF",
    "GGHHIHGF",
    "GHHIHHGG",
    "FHHHHHGF",
    "GGHHHGFF",
    "FGGHHGGF",
    "FFGGGFFF",
    "EFFFGFFE",
  ]),
  "head.front": tx(8, 8, [
    "BBBBBBBB",
    "BCDDCCBB",
    "BGGHHGGB",
    "GJKKJJHG",
    "GGHLLHGG",
    "GGMMMMGG",
    "FGGGGGGF",
    "FGHHGGFF",
  ]),
  "head.back": tx(8, 8, [
    "ABBCCBBA",
    "BBCDDCBA",
    "BCDCDDCA",
    "ACDDDCBA",
    "BCDCCDBA",
    "BBCDCBBA",
    "ABBCCBAA",
    "AABBBBAA",
  ]),
  "head.left": tx(8, 8, [
    "ABBBCCBA",
    "BBCDCCBA",
    "BCDDDCBA",
    "BGGGGGGB",
    "GGGHHHGF",
    "GGHHGGGF",
    "FGGGGGFF",
    "FFGGGFFF",
  ]),
  "head.right": tx(8, 8, [
    "ABCCBBBA",
    "ABCCDDBB",
    "ABCDDDCB",
    "BGGGGGGB",
    "FGHHHGGG",
    "FGGGHHGG",
    "FFGGGGGF",
    "FFFGGGFF",
  ]),
  "torso.front": tx(8, 12, [
    "POOQPOOP",
    "OPPPQOPO",
    "POOQPOOP",
    "OOPPRPOO",
    "OOPRRPOO",
    "PONNNNOP",
    "OPNNNNPO",
    "OONNNNOO",
    "TTTTTTTT",
    "TUTTUUTT",
    "TTUUUTTT",
    "TUTTTUTT",
  ]),
  "torso.back": tx(8, 12, [
    "OPPOQOOP",
    "POOOPQPO",
    "OPOQPOOP",
    "OPPRPOOP",
    "OOPRROPO",
    "OONNNNOO",
    "PNNNNNOP",
    "OONNNNOO",
    "TTTTTTTT",
    "TTUUTUTT",
    "TUTTTUTT",
    "TTUTTUTT",
  ]),
  "torso.left": tx(4, 12, [
    "OPOP",
    "PPQO",
    "OPPO",
    "OORO",
    "OPRO",
    "ONNO",
    "PNNO",
    "ONNO",
    "TTTT",
    "TUTT",
    "TTUT",
    "TUTT",
  ]),
  "torso.right": tx(4, 12, [
    "POPO",
    "OQPP",
    "OPPO",
    "OROO",
    "ORPO",
    "ONNO",
    "ONNP",
    "ONNO",
    "TTTT",
    "TTUT",
    "TUTT",
    "TTUT",
  ]),
  "torso.top": tx(8, 4, [
    "OPPOQOOP",
    "POOQPOOP",
    "OPPPQOPO",
    "POOPOOQP",
  ]),
  "torso.bottom": tx(8, 4, [
    "STTUTTTS",
    "TTUUUTTT",
    "TUTTTUTT",
    "STTTTUTS",
  ]),
  "rightArm.front": tx(4, 12, [
    "OQPO",
    "OPPO",
    "OPRO",
    "FHHG",
    "GGHG",
    "FGGF",
    "GGHF",
    "FGGF",
    "GGHG",
    "FHHG",
    "FGGF",
    "EFFG",
  ]),
  "rightArm.back": tx(4, 12, [
    "OPPO",
    "POQO",
    "OPRO",
    "GHGF",
    "GGFG",
    "GHHG",
    "FGGF",
    "GGHF",
    "FGGF",
    "GHHG",
    "FGGF",
    "FEFG",
  ]),
  "rightArm.left": tx(4, 12, [
    "OOPO",
    "PQOP",
    "OPRO",
    "GGHF",
    "FGGF",
    "GGHG",
    "FHHG",
    "GGFG",
    "FGGF",
    "GGHF",
    "FGGF",
    "EFFG",
  ]),
  "rightArm.right": tx(4, 12, [
    "POOO",
    "POQP",
    "ORPO",
    "FHHG",
    "GGFG",
    "FGGF",
    "GHHG",
    "FGGF",
    "GGHF",
    "FHHG",
    "GFGF",
    "FEFG",
  ]),
  "rightArm.top": tx(4, 4, [
    "OPQO",
    "POOP",
    "OPPO",
    "ROOR",
  ]),
  "rightArm.bottom": tx(4, 4, [
    "FGGF",
    "GHHG",
    "FGGF",
    "EFFG",
  ]),
  "leftArm.front": tx(4, 12, [
    "OPOQ",
    "OPPO",
    "ORPO",
    "GHHF",
    "GHGG",
    "FGGF",
    "FHGG",
    "FGGF",
    "GHGG",
    "GHHF",
    "FGGF",
    "GFFE",
  ]),
  "leftArm.back": tx(4, 12, [
    "OPPO",
    "OQOP",
    "ORPO",
    "FHGG",
    "GFGG",
    "GHHG",
    "FGGF",
    "FHGG",
    "FGGF",
    "GHHG",
    "FGGF",
    "GFEF",
  ]),
  "leftArm.left": tx(4, 12, [
    "OOOP",
    "PQOP",
    "ORPO",
    "GHHF",
    "GFGG",
    "FGGF",
    "GHHG",
    "FGGF",
    "FHGG",
    "GHHF",
    "FGFG",
    "GFEF",
  ]),
  "leftArm.right": tx(4, 12, [
    "OPOO",
    "POQP",
    "OPRO",
    "FHGG",
    "FGGF",
    "GHGG",
    "GHHF",
    "GGFG",
    "FGGF",
    "FHGG",
    "FGGF",
    "GFFE",
  ]),
  "leftArm.top": tx(4, 4, [
    "OQPO",
    "POOP",
    "OPPO",
    "ROOR",
  ]),
  "leftArm.bottom": tx(4, 4, [
    "GFGF",
    "GHHG",
    "FGGF",
    "GFFE",
  ]),
  "rightLeg.front": tx(4, 12, [
    "TUTT",
    "TTUU",
    "TUTT",
    "UTTT",
    "TTUT",
    "TUTT",
    "TTTU",
    "TUTT",
    "XXXX",
    "WXXW",
    "WWXW",
    "ZZZZ",
  ]),
  "rightLeg.back": tx(4, 12, [
    "TTUT",
    "TUTT",
    "TTUU",
    "TUTT",
    "UTTT",
    "TTUT",
    "TUTT",
    "TTTU",
    "XXXX",
    "WXWW",
    "WXXW",
    "ZZZZ",
  ]),
  "rightLeg.left": tx(4, 12, [
    "TTTU",
    "TUTT",
    "TTUT",
    "TUTT",
    "TTUU",
    "TUTT",
    "UTTT",
    "TTUT",
    "XXXX",
    "WWXW",
    "WXXW",
    "ZZZZ",
  ]),
  "rightLeg.right": tx(4, 12, [
    "UTTT",
    "TTUT",
    "TUTT",
    "TTUU",
    "TUTT",
    "UTTT",
    "TTUT",
    "TUTT",
    "XXXX",
    "WXXW",
    "WXWW",
    "ZZZZ",
  ]),
  "rightLeg.top": tx(4, 4, [
    "STTS",
    "TTUT",
    "TUTT",
    "STTS",
  ]),
  "rightLeg.bottom": tx(4, 4, [
    "WWWW",
    "WXXW",
    "WXWW",
    "ZZZZ",
  ]),
  "leftLeg.front": tx(4, 12, [
    "TTUT",
    "UUTT",
    "TTUT",
    "TTTU",
    "TUTT",
    "TTUT",
    "UTTT",
    "TTUT",
    "XXXX",
    "WXXW",
    "WXWW",
    "ZZZZ",
  ]),
  "leftLeg.back": tx(4, 12, [
    "TUTT",
    "TTUT",
    "UUTT",
    "TTUT",
    "TTTU",
    "TUTT",
    "TTUT",
    "UTTT",
    "XXXX",
    "WWXW",
    "WXXW",
    "ZZZZ",
  ]),
  "leftLeg.left": tx(4, 12, [
    "TTTU",
    "TUTT",
    "TTUT",
    "UUTT",
    "TTUT",
    "TTTU",
    "TUTT",
    "TTUT",
    "XXXX",
    "WXWW",
    "WXXW",
    "ZZZZ",
  ]),
  "leftLeg.right": tx(4, 12, [
    "UTTT",
    "TTTU",
    "TUTT",
    "TTUT",
    "UUTT",
    "TTUT",
    "TTTU",
    "TUTT",
    "XXXX",
    "WXXW",
    "WWXW",
    "ZZZZ",
  ]),
  "leftLeg.top": tx(4, 4, [
    "STTS",
    "TUTT",
    "TTUT",
    "STTS",
  ]),
  "leftLeg.bottom": tx(4, 4, [
    "WWWW",
    "WXWW",
    "WXXW",
    "ZZZZ",
  ])
} as const;
